### ISSUE TITLE
Cannot load state dict for optimizer 

### ISSUE THREAD

**Issue by huqiming513** [jfzhang95/pytorch-deeplab-xception#134]
The following error occurs when I'm trying to resume to train the model from checkpoint.
 I used the pretrained model whose backbone is ResNet provided by this repository.
```
Traceback (most recent call last):
  File "/home/qiming/workspace/pytorch-deeplab-xception/my_train.py", line 318, in <module>
    main()
  File "/home/qiming/workspace/pytorch-deeplab-xception/my_train.py", line 305, in main
    trainer = Trainer(args)
  File "/home/qiming/workspace/pytorch-deeplab-xception/my_train.py", line 95, in __init__
    self.optimizer.load_state_dict(checkpoint['optimizer'])
  File "/home/qiming/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/optim/optimizer.py", line 114, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```
When I print
```
print(self.optimizer.param_groups)
```
It shows 
```
[{'params': [Parameter containing:
tensor([[[[ 1.4587e-02,  9.5933e-04, -7.4720e-03,  ..., -6.6904e-03,
            7.3701e-04,  9.5040e-03],
          [ 2.6121e-03,  4.9495e-03, -5.4276e-03,  ..., -3.9156e-02,
           -3.4436e-02, -1.4963e-02],
          [ 4.9470e-03,  1.5524e-02,  2.6544e-02,  ...,  1.8064e-02,
            7.9475e-03,  1.7200e-02],
          ...,
          [ 1.2903e-03, -6.0330e-03, -2.8998e-03,  ..., -4.9042e-03,
            6.9914e-03, -2.5362e-04],
          [-3.0935e-03, -1.4736e-02, -5.1809e-03,  ...,  7.1390e-03,
            2.9086e-03, -1.1533e-02],
          [-3.0223e-03, -1.6870e-02, -1.5665e-02,  ..., -5.6725e-03,
           -1.9275e-02, -1.6497e-02]]]],
...,Parameter containing:
tensor([ 0.2031, -0.0163, -0.0131, -0.0167, -0.0157, -0.0165, -0.0108, -0.0070,
        -0.0026, -0.0032, -0.0179, -0.0085, -0.0044, -0.0158, -0.0137,  0.0181,
        -0.0103, -0.0173, -0.0063, -0.0112, -0.0140], device='cuda:0',
       requires_grad=True)], 'lr': 0.035, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0.0005, 'nesterov': False}]

```
and print
```
 print(checkpoint['optimizer']['param_groups'])
```
shows
```
[{'lr': 0.0003280832169020921, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0.0005, 'nesterov': False, 'params': [139745645565704, 139745645625560, 139745645626928, 139745645628296, 139745645566784, ..., 139745621150024]}, {'lr': 0.003280832169020921, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0.0005, 'nesterov': False, 'params': [139745620893344, 139745620892192, 139745620881344, 139745620878320, 139745620871280, 139745620860000, 139745620848576, 139745620845696, 139745620838512, 139745620827232, 139745620827088]}]
```
It seems that they really don't match each other, but I have no idea how to solve it. 
Could anyone tell me how to deal with the problem?

**Comment by huqiming513** [comment]
I've made following change when  loading state for optimizer.
```
  if not args.ft:
                for i in range(len(checkpoint['optimizer']['param_groups'])):
                    checkpoint['optimizer']['param_groups'][i]['params'] = torch.Tensor(
                        checkpoint['optimizer']['param_groups'][i]['params'])

                state = defaultdict(dict)
                for k, v in checkpoint['optimizer']['state'].items():
                    state[torch.tensor(k)] = v
                checkpoint['optimizer']['state'] = state
                self.optimizer.param_groups = checkpoint['optimizer']['param_groups']
                
                self.optimizer.load_state_dict(checkpoint['optimizer'])

                self.best_pred = checkpoint['best_pred']
                print("=> loaded checkpoint '{}' (epoch {})"
                      .format(args.resume, checkpoint['epoch']))
```
After that, it can be run now, whereas the training loss will increase up to 0.4**. 
After one epoch, the mIoU declines to 0.7681, the previous best of which is 0.7843. 
![image](https://user-images.githubusercontent.com/31566437/69306482-912a0580-0c62-11ea-922a-5623bc6c02b5.png)
Is that a normal loss value?

**Comment by huqiming513** [comment]
@jfzhang95 Any idea? The issue still isn't solved. After I made the change, the model weight actually cannot be trained. And I don't think what I have done is correct.

**Comment by mt-cly** [comment]
@huqiming513  https://github.com/jfzhang95/pytorch-deeplab-xception/issues/83
