### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by xysaber** [jfzhang95/pytorch-deeplab-xception#147]
**AssertionError happened when I run train_voc.sh, but I don't know how to solve this problem:**

Namespace(backbone='resnet', base_size=513, batch_size=16, checkname='deeplab-resnet', crop_size=513, cuda=False, dataset='pascal', epochs=50, eval_interval=1, freeze_bn=False, ft=False, gpu_ids='0,1,2,3', loss_type='ce', lr=0.007, lr_scheduler='poly', momentum=0.9, nesterov=False, no_cuda=False, no_val=False, out_stride=16, resume=None, seed=1, start_epoch=0, sync_bn=False, test_batch_size=16, use_balanced_weights=False, use_sbd=True, weight_decay=0.0005, workers=4)
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main()
  File "train.py", line 292, in main
    trainer = Trainer(args)
  File "train.py", line 30, in __init__
    self.train_loader, self.val_loader, self.test_loader, self.nclass = make_data_loader(args, **kwargs)
  File "/Users/xinying/Desktop/一些模型/pytorch-deeplab-xception-master/dataloaders/__init__.py", line 7, in make_data_loader
    train_set = pascal.VOCSegmentation(args, split='train')
  File "/Users/xinying/Desktop/一些模型/pytorch-deeplab-xception-master/dataloaders/datasets/pascal.py", line 52, in __init__
    assert os.path.isfile(_image)
AssertionError

**Comment by leedoge** [comment]
hello,i have the same problem! Have you solved it?thx!

**Comment by JasonChenhx** [comment]
sorry, I haven't solved it yet.
I can't download the resnet and mobilenet in the github successfully.
If you solve it, please tell me.thx



At 2020-01-09 17:51:01, "leedoge" <notifications@github.com> wrote:

hello,i have the same problem! Have you solved it?thx!

**Comment by xysaber** [comment]
make sure to set right gpu_id and workers，i changed the gpu_id=0 since i only have one gpu and set workers=1 or 2




| |
YING
邮箱：xy940311@126.com
|

Signature is customized by Netease Mail Master

On 01/09/2020 19:42, JasonChenhx wrote:
sorry, I haven't solved it yet.
I can't download the resnet and mobilenet in the github successfully.
If you solve it, please tell me.thx



At 2020-01-09 17:51:01, "leedoge" <notifications@github.com> wrote:

hello,i have the same problem! Have you solved it?thx!

**Comment by KL-Ding** [comment]
> make sure to set right gpu_id and workers，i changed the gpu_id=0 since i only have one gpu and set workers=1 or 2 | | YING 邮箱：xy940311@126.com | Signature is customized by Netease Mail Master On 01/09/2020 19:42, JasonChenhx wrote: sorry, I haven't solved it yet. I can't download the resnet and mobilenet in the github successfully. If you solve it, please tell me.thx At 2020-01-09 17:51:01, "leedoge" <notifications@github.com> wrote: hello,i have the same problem! Have you solved it?thx! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hello,i have the same problem! changing the gpu_id isn't work

**Comment by ZX815** [comment]
How to solve this problem
