### ISSUE TITLE
def make_data_loader      NotImplementedError

### ISSUE THREAD

**Issue by zhou-rui1** [jfzhang95/pytorch-deeplab-xception#188]
Namespace(backbone='mobilenet', base_size=513, batch_size=8, checkname='deeplab-mobilenet', crop_size=513, cuda=True, dataset='pascal', epochs=50, eval_interval=1, freeze_bn=False, ft=False, gpu_ids=[0], loss_type='ce', lr=0.007, lr_scheduler='poly', momentum=0.9, nesterov=False, no_cuda=False, no_val=False, out_stride=16, resume=None, seed=1, start_epoch=0, sync_bn=False, test_batch_size=8, use_balanced_weights=False, use_sbd=True, weight_decay=0.0005, workers=1)
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main()
  File "train.py", line 292, in main
    trainer = Trainer(args)
  File "train.py", line 30, in __init__
    self.train_loader, self.val_loader, self.test_loader, self.nclass = make_data_loader(args, **kwargs)
  File "/content/pytorch-deeplab-xception/dataloaders/__init__.py", line 69, in make_data_loader
    raise NotImplementedError
NotImplementedError

**Comment by praywj** [comment]
The def make_data_loader is not defined in dataloaders. This code doesnot provide this.
