### ISSUE TITLE
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4

### ISSUE THREAD

**Issue by Raymond419** [jfzhang95/pytorch-deeplab-xception#189]
Hi,all:
I face a problem 
Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main()
  File "train.py", line 296, in main
    trainer.training(epoch)
  File "train.py", line 105, in training
    loss = self.criterion(output, target)
  File "/home/shrimp/pytorch-deeplab-xception/utils/loss.py", line 28, in CrossEntropyLoss
    loss = criterion(logit, target.long())
  File "/home/shrimp/anaconda3/envs/deeplabpytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shrimp/anaconda3/envs/deeplabpytorch/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 947, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/shrimp/anaconda3/envs/deeplabpytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/shrimp/anaconda3/envs/deeplabpytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 4

could everyone give some advice to me
it seems to have some problem in  loss = self.criterion(output, target)
but i do not know how exactly fix it

**Comment by TerryBryant** [comment]
Check your target size in ```utils/loss.py``` line 28, the correct shape should be like NxHxW, check your dataloader.

**Comment by Raymond419** [comment]
Thanks for your replying, I found my dataset have something format wrong, it has been solved.
