### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Brinenas** [jfzhang95/pytorch-deeplab-xception#211]
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to C:\Users\15491/.cache\torch\hub\checkpoints\resnet101-5d3b4d8f.pth
100%|██████████| 170M/170M [01:12<00:00, 2.47MB/s]
Using poly LR Scheduler!
  0%|          | 0/366 [00:00<?, ?it/s]Starting Epoch: 0
Total Epoches: 50
  0%|          | 0/366 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:/Code/pytorch-deeplab-xception-master/train.py", line 303, in <module>
    main()
  File "D:/Code/pytorch-deeplab-xception-master/train.py", line 296, in main
    trainer.training(epoch)
  File "D:/Code/pytorch-deeplab-xception-master/train.py", line 98, in training
    for i, sample in enumerate(tbar):
  File "D:\Conda3\lib\site-packages\tqdm\std.py", line 1185, in __iter__
    for obj in iterable:
  File "D:\Conda3\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\Conda3\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "D:\Conda3\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "D:\Conda3\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Conda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Conda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Conda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\pytorch-deeplab-xception-master\dataloaders\datasets\pascal.py", line 73, in __getitem__
    return self.transform_tr(sample)
  File "D:\Code\CUHK\pytorch-deeplab-xception-master\dataloaders\datasets\pascal.py", line 92, in transform_tr
    return composed_transforms(sample)
  File "D:\Conda3\lib\site-packages\torchvision\transforms\transforms.py", line 60, in __call__
    img = t(img)
  File "D:\Code\pytorch-deeplab-xception-master\dataloaders\custom_transforms.py", line 113, in __call__
    mask = ImageOps.expand(mask, border=(0, 0, padw, padh), fill=self.fill)
  File "D:\Conda3\lib\site-packages\PIL\ImageOps.py", line 403, in expand
    draw.rectangle((0, 0, width - 1, height - 1), outline=color, width=border)
  File "D:\Conda3\lib\site-packages\PIL\ImageDraw.py", line 259, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
TypeError: an integer is required (got type tuple)
Process finished with exit code 1
 
when I use the VOC datasets to train the model, I meet this error, how can I fix this problem?

**Comment by 1160024269** [comment]
I have the same problem,have you solved it

**Comment by Brinenas** [comment]
> I have the same problem,have you solved it

nope, I have used other's model.

**Comment by 1160024269** [comment]
Have you successfully debugged with other models?Can you send the URL of your model,thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月14日(星期三) 上午9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jfzhang95/pytorch-deeplab-xception] TypeError: Caught TypeError in DataLoader worker process 0. (#211)





  
I have the same problem,have you solved it
  
nope, I have used other's model.

**Comment by Brinenas** [comment]
You can find another model for deeplabv3+:
https://gitee.com/xiaoshaKK/deep-lab-v3-plus-semantic-segmentation

**Comment by mojoee** [comment]
it is all in chinese. I coldnt find it. Do you have a more specific link?

**Comment by SmartLiam** [comment]
I have the same problem, did you have solve the problem

**Comment by sue-up** [comment]
For me, I adjusted the pillow from vision 8.3.1 to vision 8.2.0, which proved to be effective

**Comment by intlabSeJun** [comment]
> For me, I adjusted the pillow from vision 8.3.1 to vision 8.2.0, which proved to be effective

it works!! thanks i love you
