### ISSUE TITLE
self = reduction.pickle.load(from_parent) error Ran out of input

### ISSUE THREAD

**Issue by xinyujituan** [jfzhang95/pytorch-deeplab-xception#220]
File "E:\ProgramData\Anaconda3\envs\yolov5-master\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\ProgramData\Anaconda3\envs\yolov5-master\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\yolov5-master\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by 97andrea97** [comment]
Did you find the solution?
