### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size [1, 256, 1, 1]

### ISSUE THREAD

**Issue by zxshi** [jfzhang95/pytorch-deeplab-xception#41]
New code have this error.
you can change the batch_size solve this problem.

**Comment by jfzhang95** [comment]
Hi, this error is caused by AdaptiveAvgPool2d.
You can change batch_size > 1 or use model.eval() to solve it.

**Comment by zxshi** [comment]
yes. 
Thank you for your in-depth analysis.

**Comment by herleeyandi** [comment]
Hi I trained on cityscapes dataset and using batch_size=2 but after 1 iteration I got same error. Here is the complete log.
```

(deeplab_env) mspl@mspl-All-Series:~/pytorch-deeplab-xception$ python train.py --backbone resnet --lr 0.01 --workers 4 --epochs 40 --batch-size 2 --checkname deeplab-resnet --eval-interval 1 --dataset cityscapes --use-balanced-weights --checkname result_cityscapes
Namespace(backbone='resnet', base_size=513, batch_size=2, checkname='result_cityscapes', crop_size=513, cuda=True, dataset='cityscapes', epochs=40, eval_interval=1, freeze_bn=False, ft=False, gpu_ids=[0], loss_type='ce', lr=0.01, lr_scheduler='poly', momentum=0.9, nesterov=False, no_cuda=False, no_val=False, out_stride=16, resume=None, seed=1, start_epoch=0, sync_bn=False, test_batch_size=2, use_balanced_weights=True, use_sbd=True, weight_decay=0.0005, workers=4)
Found 2975 train images
Found 500 val images
Found 1525 test images
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 40
  0%|                                                  | 0/1488 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0100,                 previous best = 0.0000
/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
Train loss: 0.692: 100%|███████████████████▉| 1487/1488 [06:00<00:00,  3.97it/s]Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main()
  File "train.py", line 296, in main
    trainer.training(epoch)
  File "train.py", line 104, in training
    output = self.model(image)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mspl/pytorch-deeplab-xception/modeling/deeplab.py", line 30, in forward
    x = self.aspp(x)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mspl/pytorch-deeplab-xception/modeling/aspp.py", line 70, in forward
    x5 = self.global_avg_pool(x)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 66, in forward
    exponential_average_factor, self.eps)
  File "/home/mspl/.conda/envs/deeplab_env/lib/python3.6/site-packages/torch/nn/functional.py", line 1251, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size [1, 256, 1, 1]

```

**Comment by AlanStark** [comment]
@herleeyandi Try to set drop_last=True in dataloader? It fixed my problem.

**Comment by Maa-y** [comment]
Do you have any methods to train with batch_size=1?

**Comment by SteveIb** [comment]
@AlanStark  Hi Alan, where I should add this in code I'm not finding it.
