### ISSUE TITLE
AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'

### ISSUE THREAD

**Issue by tangyuanhenyuan** [jfzhang95/pytorch-deeplab-xception#74]
Thanks a lot for your code.

But I met this poblem when I run the train_voc.py by python3

Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main()
  File "train.py", line 296, in main
    trainer.training(epoch)
  File "train.py", line 104, in training
    output = self.model(image)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/user/新加卷/workhy/pytorch-deeplab-xception/modeling/deeplab.py", line 30, in forward
    x = self.aspp(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/user/新加卷/workhy/pytorch-deeplab-xception/modeling/aspp.py", line 71, in forward
    x5 = F.interpolate(x5, size=x4.size()[2:], mode='bilinear', align_corners=True)
AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'

Looking forward to your reply!

**Comment by pradeephike** [comment]
@tangyuanhenyuan Facing the same problem.  Can you please guide me as in what did you do to fix the problem? I am using pytorch version 0.5.0a0+4c51107
