### ISSUE TITLE
Pretrained Model not Loading

### ISSUE THREAD

**Issue by eriche7133** [jfzhang95/pytorch-deeplab-xception#83]
When I run the following line:

CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --backbone resnet --lr 0.007 --workers 4 --epochs 50 --batch-size 16 --gpu-ids 0,1,2,3 --checkname deeplab-resnet --eval-interval 1 --dataset pascal --resume 'deeplab-resnet.pth.tar'

based off of train_voc.sh, I get the following error:

Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main()
  File "train.py", line 292, in main
    trainer = Trainer(args)
  File "train.py", line 84, in __init__
    self.optimizer.load_state_dict(checkpoint['optimizer'])
  File "/home/eriche/anaconda3/envs/deeplabEnv/lib/python3.7/site-packages/torch/optim/optimizer.py", line 114, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

This is using the Resnet pretrained model downloaded from the GoogleDrive link on the README. Any help would be greatly appreciated.

**Comment by seeyouagain111** [comment]
i have the same question,have you fix it?

**Comment by kangmengmeng** [comment]
I have meet the same question,too.

**Comment by johsnows** [comment]
I have meet the same question,too.

**Comment by learningyan** [comment]
the same question.....

**Comment by xc769458796** [comment]
me too，do you resolve it?

**Comment by xc769458796** [comment]
i solved it,you should set --freeze-bn True

**Comment by CoolLoveBoy** [comment]
> i solved it,you should set --freeze-bn True

I have set --freeze-bn True, but it has the same error
